---
# =============================================================================
# Variabili specifiche per i worker nodes
# =============================================================================

# Opzioni extra per gli agent k3s
k3s_agent_extra_args: []

