---
# =============================================================================
# Variabili specifiche per i master nodes
# =============================================================================

# Il master aragorn fa anche da worker (no taint)
k3s_server_taint: false

# Opzioni extra per il server k3s
k3s_server_extra_args:
  - "--tls-san={{ k3s_master_ip }}"
  - "--tls-san=aragorn"
  - "--tls-san=aragorn.{{ internal_domain }}"
  - "--flannel-backend={{ k3s_flannel_backend }}"
  - "--disable=servicelb"
  - "--kube-apiserver-arg=service-node-port-range=30000-32767"

